--
-- Table structure for table `cws`.`news`
--

DROP TABLE IF EXISTS `cws`.`news`;
CREATE TABLE `cws`.`news` (
    `NEWS_ID` VARCHAR(128) CHARACTER SET UTF8 NOT NULL,
    `POSTING_DATE` DATE NOT NULL,
    `UNPOSTING_DATE` DATE,
    `NEWS_TITLE` TEXT CHARACTER SET UTF8 NOT NULL,
    `NEWS_SHORT_DESC` TEXT CHARACTER SET UTF8 NOT NULL,
    `NEWS_LANG` VARCHAR(2) CHARACTER SET UTF8 NOT NULL DEFAULT 'en',
    `NEWS_DESCRIPTION` TEXT CHARACTER SET UTF8 NOT NULL,
    PRIMARY KEY (`NEWS_ID`),
    FULLTEXT KEY `FK_search_jobs` (`NEWS_ID`, `NEWS_TITLE`, `NEWS_SHORT_DESC`, `NEWS_DESCRIPTION`)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COLLATE UTF8_GENERAL_CI;
COMMIT;

ALTER TABLE `cws`.`news` CONVERT TO CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
COMMIT;

DELIMITER $$

--
-- Definition of procedure `cws`.`getNewsList`
--
DROP PROCEDURE IF EXISTS `cws`.`getNewsList`$$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE `cws`.`getNewsList`(
    IN lang VARCHAR(2)
)
BEGIN
    SELECT
        NEWS_ID,
        POSTING_DATE,
        UNPOSTING_DATE,
        NEWS_TITLE,
        NEWS_SHORT_DESC,
        NEWS_LANG,
        NEWS_DESCRIPTION
    FROM `cws`.`news`
    WHERE JOB_LANG = lang
    ORDER BY POSTING_DATE DESC;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$
COMMIT$$

--
-- Definition of procedure `cws`.`getNewsItem`
--
DROP PROCEDURE IF EXISTS `cws`.`getNewsItem`$$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE `cws`.`getNewsItem`(
    IN newsId VARCHAR(128),
    IN lang VARCHAR(2)
)
BEGIN
    SELECT
        NEWS_ID,
        POSTING_DATE,
        UNPOSTING_DATE,
        NEWS_TITLE,
        NEWS_SHORT_DESC,
        NEWS_LANG,
        NEWS_DESCRIPTION
    FROM `cws`.`news`
    WHERE NEWS_ID = newsId
    AND NEWS_LANG = lang;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$
COMMIT$$

DELIMITER ;
COMMIT;
