--
-- Table structure for table `cws`.`products`
--

DROP TABLE IF EXISTS `cws`.`products`;
CREATE TABLE `cws`.`products` (
    `PRODUCT_ID` VARCHAR(128) CHARACTER SET UTF8 NOT NULL,
    `PRODUCT_NAME` VARCHAR(128) CHARACTER SET UTF8 NOT NULL,
    `PRODUCT_SHORT_DESC` TEXT CHARACTER SET UTF8 NOT NULL,
    `PRODUCT_DESC` TEXT CHARACTER SET UTF8 NOT NULL,
    `PRODUCT_PRICE` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    `PRODUCT_LANG` VARCHAR(2) CHARACTER SET UTF8 NOT NULL DEFAULT 'en',
    `IS_FEATURED` BOOLEAN NOT NULL DEFAULT FALSE,
    FULLTEXT KEY `TK_search_products` (`PRODUCT_ID`, `PRODUCT_NAME`, `PRODUCT_SHORT_DESC`, `PRODUCT_DESC`)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COLLATE UTF8_GENERAL_CI;

/*!40000 ALTER TABLE `cws`.`products` DISABLE KEYS */;
/*!40000 ALTER TABLE `cws`.`products` ENABLE KEYS */;

COMMIT;

--
-- Definition of procedure `cws`.`getProductsByAttribute`
--
DELIMITER $$
DROP PROCEDURE IF EXISTS `cws`.`getProductsByAttribute`$$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE `cws`.`getProductsByAttribute`(
    IN searchTerms VARCHAR(100),
    IN lang VARCHAR(2),
    IN startRow INT
)
BEGIN
    SELECT
        PRODUCT_ID,
        PRODUCT_NAME,
        PRODUCT_SHORT_DESC,
        PRODUCT_DESC,
        PRODUCT_PRICE,
        IS_FEATURED,
    MATCH (`PRODUCT_ID`, `PRODUCT_NAME`, `PRODUCT_SHORT_DESC`, `PRODUCT_DESC`)
    AGAINST (+searchTerms WITH QUERY EXPANSION)
    FROM `cws`.`products`
    WHERE MATCH (`PRODUCT_ID`, `PRODUCT_NAME`, `PRODUCT_SHORT_DESC`, `PRODUCT_DESC`)
    AGAINST (+searchTerms IN BOOLEAN MODE)
    AND PRODUCT_LANG = lang
    LIMIT startRow, 20;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$

DELIMITER ;
COMMIT;

--
-- Definition of procedure `cws`.`getFeaturedProducts`
--
DELIMITER $$
DROP PROCEDURE IF EXISTS `cws`.`getFeaturedProducts`$$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE `cws`.`getFeaturedProducts`(
    IN lang VARCHAR(2)
)
BEGIN
    SELECT
        PRODUCT_ID,
        PRODUCT_NAME,
        PRODUCT_SHORT_DESC,
        PRODUCT_DESC,
        PRODUCT_PRICE,
        IS_FEATURED
    FROM `cws`.`products`
    WHERE IS_FEATURED = TRUE
    AND PRODUCT_LANG = lang;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$

DELIMITER ;
COMMIT;

--
-- Definition of procedure `cws`.`getProductList`
--
DELIMITER $$
DROP PROCEDURE IF EXISTS `cws`.`getProductList`$$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE `cws`.`getProductList`(
    IN lang VARCHAR(2)
)
BEGIN
    SELECT
        PRODUCT_ID,
        PRODUCT_NAME,
        PRODUCT_SHORT_DESC,
        PRODUCT_DESC,
        PRODUCT_PRICE,
        IS_FEATURED
    FROM `cws`.`products`
    WHERE PRODUCT_LANG = lang
    ORDER BY IS_FEATURED ASC;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$

DELIMITER ;
COMMIT;

--
-- Definition of procedure `cws`.`getProductData`
--
DELIMITER $$
DROP PROCEDURE IF EXISTS `cws`.`getProductData`$$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE `cws`.`getProductData`(
    IN productId VARCHAR(128),
    IN lang VARCHAR(2)
)
BEGIN
    SELECT
        PRODUCT_ID,
        PRODUCT_NAME,
        PRODUCT_SHORT_DESC,
        PRODUCT_DESC,
        PRODUCT_PRICE,
        IS_FEATURED
    FROM `cws`.`products`
    WHERE PRODUCT_ID = productId
    AND PRODUCT_LANG = lang;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$

DELIMITER ;
COMMIT;
