--
-- Definition of table `cws`.`email_messages`
--
DROP TABLE IF EXISTS `cws`.`email_messages`;
CREATE TABLE `cws`.`email_messages` (
    `EMAIL_MESSAGE_ID` VARCHAR(128) CHARACTER SET UTF8 NOT NULL UNIQUE,
    `EMAIL_MESSAGE_DATE` BIGINT NOT NULL,
    `EMAIL_MESSAGE_FROM` VARCHAR(100) CHARACTER SET UTF8 NOT NULL,
    `EMAIL_MESSAGE_TO` VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
    `EMAIL_MESSAGE_CC` VARCHAR(255)CHARACTER SET UTF8,
    `EMAIL_MESSAGE_BCC` VARCHAR(255)CHARACTER SET UTF8,
    `EMAIL_MESSAGE_SOURCES` TEXT CHARACTER SET UTF8 NOT NULL,
    `EMAIL_MESSAGE_SUBJECT` VARCHAR(255) CHARACTER SET UTF8,
    `EMAIL_MESSAGE_BODY` TEXT CHARACTER SET UTF8 NOT NULL,
    `EMAIL_MESSAGE_ATTACHMENTS` BLOB,
    PRIMARY KEY  (`EMAIL_MESSAGE_ID`),
    FULLTEXT KEY `EMAIL_SEARCH` (`EMAIL_MESSAGE_FROM`, `EMAIL_MESSAGE_BODY`, `EMAIL_MESSAGE_SUBJECT`, `EMAIL_MESSAGE_SOURCES`)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COLLATE UTF8_GENERAL_CI;
COMMIT;

ALTER TABLE `cws`.`email_messages` CONVERT TO CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
COMMIT;

DELIMITER $$

--
-- Definition of procedure `cws`.`getEmailByAttribute`
--
DROP PROCEDURE IF EXISTS `cws`.`getEmailByAttribute`$$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE `cws`.`getEmailByAttribute`(
    IN attributeName VARCHAR(100)
)
BEGIN
    SELECT
        EMAIL_MESSAGE_ID,
        EMAIL_MESSAGE_DATE,
        EMAIL_MESSAGE_FROM,
        EMAIL_MESSAGE_TO,
        EMAIL_MESSAGE_CC,
        EMAIL_MESSAGE_BCC,
        EMAIL_MESSAGE_SOURCES,
        EMAIL_MESSAGE_SUBJECT,
        EMAIL_MESSAGE_BODY,
        EMAIL_MESSAGE_ATTACHMENTS,
    MATCH (`EMAIL_MESSAGE_FROM`, `EMAIL_MESSAGE_BODY`, `EMAIL_MESSAGE_SUBJECT`, `EMAIL_MESSAGE_SOURCES`)
    AGAINST (+attributeName WITH QUERY EXPANSION)
    FROM `cws`.`email_messages`
    WHERE MATCH (`EMAIL_MESSAGE_FROM`, `EMAIL_MESSAGE_BODY`, `EMAIL_MESSAGE_SUBJECT`, `EMAIL_MESSAGE_SOURCES`)
    AGAINST (+attributeName IN BOOLEAN MODE);
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$
COMMIT$$

--
-- Definition of procedure `cws`.`insertEmailMessage`
--
DROP PROCEDURE IF EXISTS `cws`.`insertEmailMessage`$$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE `cws`.`insertEmailMessage`(
    IN messageId VARCHAR(128),
    IN messageDate BIGINT,
    IN messageFrom VARCHAR(255),
    IN messageTO VARCHAR(255),
    IN messageCC VARCHAR(255),
    IN messageBCC VARCHAR(255),
    IN sources TEXT,
    IN messageSubject VARCHAR(255),
    IN messageBody TEXT,
    IN attachments BLOB
)
BEGIN
    INSERT INTO `cws`.`email_messages`
    (
        EMAIL_MESSAGE_ID, EMAIL_MESSAGE_DATE, EMAIL_MESSAGE_FROM, EMAIL_MESSAGE_TO, EMAIL_MESSAGE_CC,
        EMAIL_MESSAGE_BCC, EMAIL_MESSAGE_SOURCES, EMAIL_MESSAGE_SUBJECT, EMAIL_MESSAGE_BODY, EMAIL_MESSAGE_ATTACHMENTS
    )
    VALUES
    (
        messageId, messageDate, messageFrom, messageTO, messageCC,
        messageBCC, sources, messageSubject, messageBody, attachments
    );

    COMMIT;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$
COMMIT$$

--
-- Definition of procedure `cws`.`retrieve_email_count`
--
DROP PROCEDURE IF EXISTS `cws`.`retrieve_email_count`$$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE `cws`.`retrieve_email_count`(
)
BEGIN
    SELECT COUNT(EMAIL_MESSAGE_ID)
    FROM `cws`.`email_messages`;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$
COMMIT$$

--
-- Definition of procedure `cws`.`retrieveMessages`
--
DROP PROCEDURE IF EXISTS `cws`.`retrieveMessages`$$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE `cws`.`retrieveMessages`(
)
BEGIN
    SELECT
        EMAIL_MESSAGE_ID,
        EMAIL_MESSAGE_DATE,
        EMAIL_MESSAGE_FROM,
        EMAIL_MESSAGE_TO,
        EMAIL_MESSAGE_CC,
        EMAIL_MESSAGE_BCC,
        EMAIL_MESSAGE_SOURCES,
        EMAIL_MESSAGE_SUBJECT,
        EMAIL_MESSAGE_BODY,
        EMAIL_MESSAGE_ATTACHMENTS
    FROM `cws`.`email_messages`;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$
COMMIT$$

--
-- Definition of procedure `cws`.`retrieveMessage`
--
DROP PROCEDURE IF EXISTS `cws`.`retrieveMessage`$$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE `cws`.`retrieveMessage`(
    IN messageId VARCHAR(100)
)
BEGIN
    SELECT
        EMAIL_MESSAGE_ID,
        EMAIL_MESSAGE_DATE,
        EMAIL_MESSAGE_FROM,
        EMAIL_MESSAGE_TO,
        EMAIL_MESSAGE_CC,
        EMAIL_MESSAGE_BCC,
        EMAIL_MESSAGE_SOURCES,
        EMAIL_MESSAGE_SUBJECT,
        EMAIL_MESSAGE_BODY,
        EMAIL_MESSAGE_ATTACHMENTS
    FROM `cws`.`email_messages`
    WHERE EMAIL_MESSAGE_ID = messageId;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$
COMMIT$$

DELIMITER ;
COMMIT;
