--
-- Definition of table `cws`.`site_search`
--
DROP TABLE IF EXISTS `CWS`.`SITE_SEARCH`;
CREATE TABLE `CWS`.`SITE_SEARCH` (
  `SEARCH_TERMS` VARCHAR(100) CHARACTER SET UTF8 NOT NULL DEFAULT '',
  `PAGE_TITLE` VARCHAR(45) CHARACTER SET UTF8 NOT NULL DEFAULT '',
  `PAGE_URL` VARCHAR(45) CHARACTER SET UTF8 NOT NULL DEFAULT '',
  `PAGE_DESC` VARCHAR(45) CHARACTER SET UTF8 NOT NULL DEFAULT '',
  `PAGE_LANG` VARCHAR(45) CHARACTER SET UTF8 NOT NULL DEFAULT '',
  FULLTEXT KEY `SEARCH` (`SEARCH_TERMS`,`PAGE_TITLE`,`PAGE_URL`,`PAGE_DESC`)
) ENGINE=MYISAM DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COLLATE UTF8_GENERAL_CI;
COMMIT;

ALTER TABLE `cws`.`site_search` CONVERT TO CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
COMMIT;

DELIMITER $$

--
-- Definition of procedure `cws`.`getPageByAttribute`
--
DROP PROCEDURE IF EXISTS `cws`.`getPageByAttribute`$$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE `cws`.`getPageByAttribute`(
    IN searchTerms VARCHAR(100)
)
BEGIN
    SELECT page_url, page_title,
    MATCH (search_terms, page_title, page_url, page_desc)
    AGAINST (+searchTerms WITH QUERY EXPANSION)
    FROM `cws`.`site_search`
    WHERE MATCH (search_terms, page_title, page_url, page_desc)
    AGAINST (+searchTerms IN BOOLEAN MODE);
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$
COMMIT $$

DELIMITER ;
COMMIT;
